services:

  db:
    image: postgres:18-alpine
    container_name: x-notes-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - x-notes-db:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./data:/home/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: x-notes-adminer
    scale: 0
    restart: always
    environment:
      ADMINER_DESIGN: "hever"
    ports:
      - "8082:8080"
    depends_on:
      - db

  postgrest:
    image: postgrest/postgrest
    container_name: x-notes-postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres@db:5432/postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_AGGREGATES_ENABLED: "true"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    container_name: x-notes-swagger
    scale: 0
    ports:
      - "8081:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - postgrest

  nginx:
    image: nginx:alpine
    container_name: x-notes-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./www:/home/www
    command: /bin/sh -c "sed -e 's/__POSTGREST__/postgrest/g' -e 's/__API__/api/g' /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - postgrest
      - api

  api:
    build:
      context: ./cmd/api
      dockerfile: Dockerfile
    container_name: x-notes-api
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./data:/home/data

volumes:
  x-notes-db:
    name: x-notes-db
    external: true
